import { ServerStatus } from '../components/pure/serverStatus';
import { SupportBtn } from '../components/pure/support';
import { UserView } from '../components/pure/userView';
import '../globals.css';
import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={'min-h-screen'}>
      <header className="flex justify-between p-10">
        <ServerStatus />
        <UserView />
      </header>
      {children}
      <SupportBtn />
    </div>
  );
}
