import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const links = [
  {
    label: 'Home',
    route: '/'
  }
];

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <Head>
        <title>Ticketera</title>
      </Head>
      <body className={'min-h-screen'}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
