import { ServerStatus } from '../components/pure/serverStatus';
import { SupportBtn } from '../components/pure/support';
import { UserView } from '../components/pure/userView';
import '../globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const links = [
  {
    label: 'Home',
    route: '/'
  }
];

export default function AdminLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Ticketera</title>
      </head>
      <body className={inter.className + ' min-h-screen'}>
        <header className="flex justify-between p-10">
          <ServerStatus />
          <UserView />
        </header>
        {children}
        <SupportBtn />
      </body>
    </html>
  );
}
